openapi: 3.0.0
info:
  title: Membership API
  version: 1.0.0
  description: API for managing memberships
paths:
  # /auth/register:
  #   post:
  #     summary: Register a new user
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/UserCredentials'
  #     responses:
  #       '200':
  #         description: User registered successfully
  #       '400':
  #         description: Validation error

  # /auth/login:
  #   post:
  #     summary: Login a user
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/UserCredentials'
  #     responses:
  #       '200':
  #         description: Login successful
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/UserLoginResponse'
  #       '401':
  #         description: Invalid credentials

  # /auth/logout:
  #   get:
  #     summary: Logout the current user
  #     security:
  #       - bearerAuth: []
  #     responses:
  #       '200':
  #         description: Logout successful
  #       '401':
  #         description: Unauthorized

  /memberships:
    get:
      summary: List all memberships
      operationId: listMemberships
      responses:
        '200':
          description: A list of memberships with their periods
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MembershipWithPeriods'
    post:
      summary: Create a new membership
      operationId: createMembership
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembershipInput'
      responses:
        '201':
          description: Created membership with periods
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembershipCreationResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    MembershipState:
      type: string
      enum: [active, pending, expired]
    BillingInterval:
      type: string
      enum: [weekly, monthly, yearly]
    PaymentMethod:
      type: string
      enum: [cash, credit, debit, bank_transfer]
    MembershipPeriodState:
      type: string
      enum: [planned, active, expired]
    MembershipInput:
      type: object
      required:
        - name
        - recurringPrice
        - billingPeriods
        - billingInterval
      properties:
        name:
          type: string
        recurringPrice:
          type: number
          minimum: 0
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        billingPeriods:
          type: integer
          minimum: 1
          maximum: 12
        billingInterval:
          $ref: '#/components/schemas/BillingInterval'
        validFrom:
          type: string
          format: date-time
    # UserLogin:
    #   type: object
    #   properties:
    #     id:
    #       type: integer
    #     email:
    #       type: string
    #       format: uuid
    #     token:
    #       type: string
    #   required:
    #     - id
    #     - email
    #     - token
    Membership:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
          format: uuid
        name:
          type: string
        state:
          $ref: '#/components/schemas/MembershipState'
        validFrom:
          type: string
          format: date-time
        validUntil:
          type: string
          format: date-time
        user:
          type: integer
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        recurringPrice:
          type: number
        billingPeriods:
          type: integer
        billingInterval:
          $ref: '#/components/schemas/BillingInterval'
    MembershipPeriod:
      type: object
      properties:
        id:
          type: integer
        uuid:
          type: string
          format: uuid
        membershipId:
          type: integer
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        state:
          $ref: '#/components/schemas/MembershipPeriodState'
    MembershipWithPeriods:
      type: object
      properties:
        membership:
          $ref: '#/components/schemas/Membership'
        periods:
          type: array
          items:
            $ref: '#/components/schemas/MembershipPeriod'
    # UserLoginResponse:
    #   type: object
    #   properties:
    #     membership:
    #       $ref: '#/components/schemas/UserLogin'
    MembershipCreationResponse:
      type: object
      properties:
        membership:
          $ref: '#/components/schemas/Membership'
        membershipPeriods:
          type: array
          items:
            $ref: '#/components/schemas/MembershipPeriod'
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          enum:
            - missingMandatoryFields
            - negativeRecurringPrice
            - cashPriceBelow100
            - billingPeriodsMoreThan12Months
            - billingPeriodsLessThan6Months
            - billingPeriodsMoreThan10Years
            - billingPeriodsLessThan3Years
            - invalidBillingPeriods
    # UserCredentials:
    #   type: object
    #   required:
    #     - email
    #     - password
    #   properties:
    #     email:
    #       type: string
    #       format: email
    #     password:
    #       type: string
    #       minLength: 6
