/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all memberships */
        get: operations["listMemberships"];
        put?: never;
        /** Create a new membership */
        post: operations["createMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        MembershipState: MembershipState;
        /** @enum {string} */
        BillingInterval: BillingInterval;
        /** @enum {string} */
        PaymentMethod: PaymentMethod;
        /** @enum {string} */
        MembershipPeriodState: MembershipPeriodState;
        MembershipInput: {
            name: string;
            recurringPrice: number;
            paymentMethod?: components["schemas"]["PaymentMethod"];
            billingPeriods: number;
            billingInterval: components["schemas"]["BillingInterval"];
            /** Format: date-time */
            validFrom?: string;
        };
        Membership: {
            id?: number;
            /** Format: uuid */
            uuid?: string;
            name?: string;
            state?: components["schemas"]["MembershipState"];
            /** Format: date-time */
            validFrom?: string;
            /** Format: date-time */
            validUntil?: string;
            user?: number;
            paymentMethod?: components["schemas"]["PaymentMethod"];
            recurringPrice?: number;
            billingPeriods?: number;
            billingInterval?: components["schemas"]["BillingInterval"];
        };
        MembershipPeriod: {
            id?: number;
            /** Format: uuid */
            uuid?: string;
            membershipId?: number;
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
            state?: components["schemas"]["MembershipPeriodState"];
        };
        MembershipWithPeriods: {
            membership?: components["schemas"]["Membership"];
            periods?: components["schemas"]["MembershipPeriod"][];
        };
        MembershipCreationResponse: {
            membership?: components["schemas"]["Membership"];
            membershipPeriods?: components["schemas"]["MembershipPeriod"][];
        };
        ErrorResponse: {
            /** @enum {string} */
            message?: ErrorResponseMessage;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of memberships with their periods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipWithPeriods"][];
                };
            };
        };
    };
    createMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipInput"];
            };
        };
        responses: {
            /** @description Created membership with periods */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCreationResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
export enum MembershipState {
    active = "active",
    pending = "pending",
    expired = "expired"
}
export enum BillingInterval {
    weekly = "weekly",
    monthly = "monthly",
    yearly = "yearly"
}
export enum PaymentMethod {
    cash = "cash",
    credit = "credit",
    debit = "debit",
    bank_transfer = "bank_transfer"
}
export enum MembershipPeriodState {
    planned = "planned",
    active = "active",
    expired = "expired"
}
export enum ErrorResponseMessage {
    missingMandatoryFields = "missingMandatoryFields",
    negativeRecurringPrice = "negativeRecurringPrice",
    cashPriceBelow100 = "cashPriceBelow100",
    billingPeriodsMoreThan12Months = "billingPeriodsMoreThan12Months",
    billingPeriodsLessThan6Months = "billingPeriodsLessThan6Months",
    billingPeriodsMoreThan10Years = "billingPeriodsMoreThan10Years",
    billingPeriodsLessThan3Years = "billingPeriodsLessThan3Years",
    invalidBillingPeriods = "invalidBillingPeriods"
}
